### ISSUE TITLE
Error generating REST configuration: invalid configuration: [unable to read client-cert /Users/xxx/.minikube/profiles/minikube/client.crt

### ISSUE THREAD

**Issue by tianmingxing** [txn2/kubefwd#227] opened 2022-04-29 03:11 UTC
error output: 

```
INFO[03:02:56] HostFile management: Backing up your original hosts file /etc/hosts to /root/hosts.original
FATA[03:02:56] Error generating REST configuration: invalid configuration: [unable to read client-cert /Users/xxx/.minikube/profiles/minikube/client.crt for minikube due to open /Users/xxx/.minikube/profiles/minikube/client.crt: no such file or directory, unable to read client-key /Users/xxx/.minikube/profiles/minikube/client.key for minikube due to open /Users/xxx/.minikube/profiles/minikube/client.key: no such file or directory, unable to read certificate-authority /Users/xxx/.minikube/ca.crt for minikube due to open /Users/xxx/.minikube/ca.crt: no such file or directory]
```

These files are real and readable: 

```
 xxx  ~  ll /Users/xxx/.minikube/profiles/minikube/client.crt
-rw-r--r--  1 xxx  staff   1.1K  4 15 12:41 /Users/xxx/.minikube/profiles/minikube/client.crt
 xxx  ~  ll /Users/xxx/.minikube/ca.crt
-rw-r--r--  1 xxx  staff   1.1K  4 15 12:41 /Users/xxx/.minikube/ca.crt
```

**Comment by cjimti** [comment] 2022-04-30 01:49
What user are you executing `kubefwd` with? What operating system are you using? I don't really have enough information to give you any good suggestions.

**Comment by tianmingxing** [comment] 2022-05-13 11:13
> What user are you executing `kubefwd` with? What operating system are you using? I don't really have enough information to give you any good suggestions.

Executive user：xxx
I tried to add sudo, but it's still the same problem.

**Comment by cjimti** [comment] 2022-05-14 01:31
you might need to try `sudo -E` again I don't know what operating system or anything else about your configuration. `kubefwd` claims that there is `/Users/xxx/.minikube/ca.crt: no such file or directory` so you may have something protecting that from being accessed or running the command from a container or a sandbox.

I'm closing this issues since this is not a bug in `kubefwd`.

**Closed by cjimti** 2022-05-14 01:31 UTC
