### ISSUE TITLE
kubefwd not working on minikube

### ISSUE THREAD

**Issue by ominibyte** [txn2/kubefwd#130] opened 2020-06-24 01:13 UTC
I just found out about kubefwd and decided to try it out on my minikube cluster running on virtualbox on OSX but it doesn't seem to be doing the actual forwarding. It reports that it is forwarding and the services listed are correct but when I try to access the port from the host it doesn't work. I have tried with `kubectl port-forward` and it works perfectly. 

Here's the output on the terminal if it will help.

```
$ sudo kubefwd services -n default
Password:
INFO[20:52:39]  _          _           __             _     
INFO[20:52:39] | | ___   _| |__   ___ / _|_      ____| |    
INFO[20:52:39] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |    
INFO[20:52:39] |   <| |_| | |_) |  __/  _|\ V  V / (_| |    
INFO[20:52:39] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|    
INFO[20:52:39]                                              
INFO[20:52:39] Version 1.14.2                               
INFO[20:52:39] https://github.com/txn2/kubefwd              
INFO[20:52:39]                                              
INFO[20:52:40] Press [Ctrl-C] to stop forwarding.           
INFO[20:52:40] 'cat /etc/hosts' to see all host entries.    
INFO[20:52:40] Loaded hosts file /etc/hosts                 
INFO[20:52:40] Hostfile management: Original hosts backup already exists at /Users/richboy/hosts.original 
INFO[20:52:40] Succesfully connected context: minikube      
INFO[20:52:40] Port-Forward: couchbase-cluster-service:8091 to pod couchbase-cluster-0:8091 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:8092 to pod couchbase-cluster-0:8092 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:8093 to pod couchbase-cluster-0:8093 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:8094 to pod couchbase-cluster-0:8094 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:8095 to pod couchbase-cluster-0:8095 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:8096 to pod couchbase-cluster-0:8096 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:11210 to pod couchbase-cluster-0:11210 
INFO[20:52:40] Port-Forward: couchbase-cluster-service:11211 to pod couchbase-cluster-0:11211 
WARN[20:52:40] WARNING: No Pod selector for service kubernetes in default on cluster . 
INFO[20:52:40] Port-Forward: redis-cluster-service:6379 to pod redis-cluster-0:6379 
INFO[20:52:40] Port-Forward: redis-cluster-service:6379 to pod redis-cluster-0:6379
```

What could be the issue? Any help is appreciated.

Thank you.

**Comment by cjimti** [comment] 2020-10-27 19:29
@ominibyte can you update to the latest version 1.17.2. If you are still having trouble please post the portion on /etc/hosts added by `kubefwd` while it's running. Thanks

**Comment by balibebas** [comment] 2020-12-14 03:46
@ominibyte Since you're macOS have you considered using K3D/KiND as opposed to Minikube?

**Comment by cjimti** [comment] 2021-09-23 08:12
I just installed minikube on linux (my main workstation) and have no problems running `kubefwd` against it. 

```
INFO[01:05:22]  _          _           __             _     
INFO[01:05:22] | | ___   _| |__   ___ / _|_      ____| |    
INFO[01:05:22] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |    
INFO[01:05:22] |   <| |_| | |_) |  __/  _|\ V  V / (_| |    
INFO[01:05:22] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|    
INFO[01:05:22]                                              
INFO[01:05:22] Version 1.21.0                               
INFO[01:05:22] https://github.com/txn2/kubefwd              
INFO[01:05:22]                                              
INFO[01:05:22] Press [Ctrl-C] to stop forwarding.           
INFO[01:05:22] 'cat /etc/hosts' to see all host entries.    
INFO[01:05:22] Loaded hosts file /etc/hosts                 
INFO[01:05:22] HostFile management: Original hosts backup already exists at /home/craig/hosts.original 
INFO[01:05:22] Using namespace default from current context minikube. 
INFO[01:05:22] Successfully connected context: minikube     
WARN[01:05:22] WARNING: No Pod selector for service kubernetes.default, skipping 
INFO[01:05:22] Port-Forward: 127.1.27.1 http-test:8080 to pod http-test-785656689b-gr2cq:80 
```

```
$ curl http://http-test:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

I'll close this ticket for now but can open it if I can get more information on how to reproduce. 

Are you still having this issue?

**Closed by cjimti** 2021-09-23 08:12 UTC
Labels: question
