### ISSUE TITLE
openshift incompatibility -connection refused

### ISSUE THREAD

**Issue by cforce** [txn2/kubefwd#26] opened 2018-11-25 15:53 UTC
I can can't connect where i can do via oc and kubectl

kubectl get services -n project            -> works
sudo kubefwd services -l -n project    -> dial tcp xxx.xxxx.xxxx: connect: connection refused

Maybe it's also a http proxy issue ?

**Comment by cjimti** [comment] 2018-11-26 15:54
Any more information on this would be helpful. I don't use Open Shift.

**Comment by latchmihay** [comment] 2018-11-27 21:13
The issue is with your `$KUBECONFIG`. You are most likely using a custom Kube Config location and not the default `$HOME/.kube/config` 

You have to use the `-E` option with sudo in order for your environment variables to persist

>        -E, --preserve-env
>                   Indicates to the security policy that the user wishes to preserve their existing environment variables.  The security policy may return an error if the user does not have permission to
>                   preserve the environment.

Troubleshooting:
```console
$ kubefwd svc --help
...
...
  -c, --kubeconfig string   absolute path to a kubectl config file (default "/Users/latch/.kube/k8s-config-np")
...

$ sudo kubefwd svc --help
...
...
  -c, --kubeconfig string   absolute path to a kubectl config file (default "/Users/latch/.kube/config")
...
```

**Comment by cjimti** [comment] 2018-11-28 06:46
Thanks @latchmihay I'm going to close this issue. @cforce if you continue to have trouble connecting please create a new issue with more detail.

**Closed by cjimti** 2018-11-28 06:46 UTC
Labels: help wanted
