### ISSUE TITLE
Is Docker for Mac supported?

### ISSUE THREAD

**Issue by cchanning** [txn2/kubefwd#53] opened 2019-04-01 14:54 UTC
Hi,

Firstly, great tool! 

Quick question, I followed this example for getting Kafka running: https://imti.co/kafka-kubernetes/. I'm using Docker For Mac (2.0.0.3). When running kubefwd, I get the following output:

<img width="849" alt="Screenshot 2019-04-01 at 15 49 58" src="https://user-images.githubusercontent.com/753647/55337053-db713300-5495-11e9-99f2-b6a56d36a686.png">

I am successfully able to create a new Kafka topic:
/kafka-topics.sh --zookeeper kafka-zookeeper:2181 \
--topic test --create --partitions 1 --replication-factor 1

But when trying to post a message to the topic using the following command, I receive a timeout error:

Tried with:
/kafka-console-producer.sh --topic test --broker-list kafka-headless:9092
/kafka-console-producer.sh --topic test --broker-list kafka:9092

Error:
[2019-04-01 15:50:49,755] WARN [Producer clientId=console-producer] Connection to node 0 (/10.1.0.117:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

My hosts file looks as follows:

127.1.27.1       kafka kafka.the-project kafka.the-project.svc.cluster.local
127.1.27.2       kafka-headless kafka-headless.the-project kafka-headless.the-project.svc.cluster.local
127.1.27.3       kafka-zookeeper kafka-zookeeper.the-project kafka-zookeeper.the-project.svc.cluster.local
127.1.27.4       kafka-zookeeper-headless kafka-zookeeper-headless.the-project kafka-zookeeper-headless.the-project.svc.cluster.local

If I post from within a container, then I have no issues.

Am I missing something?

**Comment by cchanning** [comment] 2019-04-01 16:17
I also tried:

./kafka-broker-api-versions.sh --bootstrap-server kafka:9092
./kafka-broker-api-versions.sh --bootstrap-server kafka-headless:9092

Both yielded with:
10.1.0.117:9092 (id: 0 rack: null) -> ERROR: org.apache.kafka.common.errors.TimeoutException: Failed to send request after 5000 ms.

**Comment by sgandon** [comment] 2019-04-01 17:09
I think the pb comes from you kafka setup
Kafka broadcast it's adress to the client so the client can use it and the adress broadcasted in IP internal to your cluster.

**Comment by sgandon** [comment] 2019-04-01 17:10
You should be able to configure the broker to broadcast `kafka` as an adress.

**Comment by cjimti** [comment] 2019-04-02 02:51
@sgandon sounds like good advice.

I'm also closing as a duplicate of #52 I'll try to make time in a new few days to work on a fix.

**Closed by cjimti** 2019-04-02 02:51 UTC

**Comment by cchanning** [comment] 2019-04-02 09:49
Thanks @sgandon, I found this highly useful and detailed article to walk me through Kafka listener setup: https://rmoff.net/2018/08/02/kafka-listeners-explained/
