### ISSUE TITLE
Could /etc/hosts be cleaned without losing other changes?

### ISSUE THREAD

**Issue by solsson** [txn2/kubefwd#75] opened 2019-08-20 04:52 UTC
We use `kubefwd` in combination with [Glasses](https://github.com/wakeful/glasses) (actually an alternative build [k8s-ingress-hosts](https://github.com/solsson/k8s-ingress-hosts/)). When kubefwd exits it will reset changes made by Glasses as well. Glasses on the contrary removes only its own entries.

What glasses does is it generates markers `# generated using glasses start #` and `# generated using glasses end #` (see also https://github.com/solsson/k8s-ingress-hosts/commit/ae424643e32f0ce2188a468ef196e53fadf7c2e1). Could kubefwd do the same thing?

**Comment by cjimti** [comment] 2019-08-21 02:59
`kubefwd` only removes hostnames it adds. If those same hostnames already exist or duplicates are added you will get unexpected behavior. 

I do need to perform some checks to ensure a hostname does not already exist and probably issue a prompt if a user wishes to overwrite it. If `kubefwd` is removing entries added by another system then they are duplicate entries. For example, if kubefwd added "`127.1.27.10 grafana.local`" it will remove the entry "portal" since technically there should only be one and it would have been added by kubefwd. If another system adds for example "`192.168.99.100 grafana.local`" then you have duplicate entries, and your system will only use the first one. The expected behavior is dependant on execution order (a race condition).

Having multiple systems write to `/etc/hosts` concurrently is always going to be a risk. 

Another check I can do would be to limit removing a hostname if it is assigned to an IP outside of the expected range and again this would need to warn the user of unexpected behavior.

**Comment by atamon** [comment] 2019-08-21 15:29
Hi @cjimti,

Super cool tool you've built here! I thought I'd clarify @solsson's issue with some more insights:
We have two different tools writing to /etc/hosts. They don't write to the file concurrently, but I've noticed that kubefwd seems to save a "backup" file at $HOME/hosts.backup which I guess is used for removing the lines kubefwd adds.

This scenario reproduces the issue we're having:

1. `kubefwd svc ...`
2. In a new terminal: `echo "127.0.0.1 dev.local" >> /etc/hosts`
3. Cancel `kubefwd`
4. My line from the second step is gone

The same problem seems to arise wherever I add a new line, not just if I put it at the bottom of /etc/hosts.

Please let us know if this is anything that you plan on supporting. Thanks in advance!

**Comment by cjimti** [comment] 2019-08-21 16:21
`$HOME/hosts.backup` is only created once as a safety-net and is not used. It is only created again if the user deletes it. 

Unless kubefwd previously added `dev.local` it is a bug. I'll look at this today! If you are curious, I use [txeh](https://github.com/txn2/txeh) to manage `/etc/hosts`.

**Comment by cjimti** [comment] 2019-08-21 16:32
@solsson @atamon I confirmed the condition you reported. `kubefwd` needs to reload current the `/etc/hosts` content before it cleans it. It should be an easy fix and I can add it after reviewing a PR that involves this part of code as well. 

Thanks for finding this. :thumbsup:

**Comment by atamon** [comment] 2019-08-21 16:38
@cjimti :beers:

Thanks for the quick replies and thorough explanations!

**Comment by cjimti** [comment] 2019-08-25 07:50
Thank you for the bug report. This should now be fixed in the release [1.9.1](https://github.com/txn2/kubefwd/releases/tag/v1.9.1).

**Closed by cjimti** 2019-08-25 07:50 UTC
Labels: bug
