### ISSUE TITLE
kubefwd exits when there is a completed pod 

### ISSUE THREAD

**Issue by turkenh** [txn2/kubefwd#34] opened 2019-01-07 12:33 UTC
When there are completed pods (which belongs to a job), kubefwd exits as follows:

$ sudo kubefwd svc --namespace default
2019/01/07 15:30:50  _          _           __             _
2019/01/07 15:30:50 | | ___   _| |__   ___ / _|_      ____| |
2019/01/07 15:30:50 | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
2019/01/07 15:30:50 |   <| |_| | |_) |  __/  _|\ V  V / (_| |
2019/01/07 15:30:50 |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
2019/01/07 15:30:50
2019/01/07 15:30:50 Version 1.4.10
2019/01/07 15:30:50 https://github.com/txn2/kubefwd
2019/01/07 15:30:50
2019/01/07 15:30:50 Press [Ctrl-C] to stop forwarding.
2019/01/07 15:30:50 'cat /etc/hosts' to see all host entries.
2019/01/07 15:30:50 Loaded hosts file /etc/hosts
2019/01/07 15:30:50 Hostfile management: Original hosts backup already exists at /etc/hosts.original
2019/01/07 15:30:50 Forwarding: kubernetes:443 to pod my-job-p7sqj:443
2019/01/07 15:30:51 ERROR: error upgrading connection: unable to upgrade connection: pod not found ("my-job-p7sqj_default")
2019/01/07 15:30:51 Stopped forwarding kubernetes in default.
2019/01/07 15:30:51 Done..

$ kubectl get pods
NAME                                        READY     STATUS      RESTARTS   AGE
my-job-p7sqj                            0/1       Completed   0          11m

**Comment by cjimti** [comment] 2019-01-07 21:39
The problem looks related to #35 although you reported this first I believe the issue is actually with how I find pods for a service using the selector. The "kubernetes" service it's finding in your default namespace does not use selectors so for some reason I'm picking up on a pod (in this case a pod that is not running). 

I am going to close this as a duplicate of #35  for now and focus on fixing that. It should resolve your issue once I find a solution to #35.

**Closed by cjimti** 2019-01-07 21:39 UTC
