### ISSUE TITLE
Go Build errors on FreeBSD

### ISSUE THREAD

**Issue by chfrank-cgn** [txn2/kubefwd#25] opened 2018-11-24 14:17 UTC
I'm trying to build kubefwd on FreeBSD and it fails with the following compile time errors:

```
go build kubefwd/kubefwd.go
# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:246:13: cannot use expiresIn (type string) as type json.Number in field value
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:247:13: cannot use expiresOn (type string) as type json.Number in field value
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:248:13: cannot use expiresOn (type string) as type json.Number in field value
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:265:23: cannot use token.token.ExpiresIn (type json.Number) as type string in assignment
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:266:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment
```

Any ideas? Thank you!

**Comment by cjimti** [comment] 2018-11-24 18:05
This looks the Azure auth plugin is having trouble. I would ask the team over at https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/azure

It does not reproduce for me. What version of Go are you using? Does the binary release work?

I am going to close this ticket since I don't believe it's a bug in this codebase. Although I will re-open if there is something I can change to make this work for you.

**Closed by cjimti** 2018-11-24 18:05 UTC
